### PR TITLE
More formatting hints

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by KristofferC** [comment]
Tell me the magic commands to format my code :P

**Comment by ZacLN** [comment]
pull [this](https://github.com/ZacLN/julia-vscode/tree/update-lsp) fork of julia-vscode (it won't get merged until there's a proper julia 0.6) in your  `.vscode/extensions` folder and run 'Format document`! 

Next up is auto-fix for deprecations but more suggestions are welcome!

**Comment by KristofferC** [comment]
Hm, having some problems with for example `command 'language-julia.toggleLinter' not found`and similar for all other commands. I'll just wait for official release :)

**Comment by ZacLN** [comment]
Eek, the linter command needs removing. What other command failed?

**Comment by KristofferC** [comment]
The `weave` commands, the open package, in new window command, the run tests command. I also can't find the "format document" when writing "format" in the action menu.

**Comment by ZacLN** [comment]
Ah sounds like some version mismatching

**Pull request merged**
