### PR TITLE
remove junk file, add Tokenize

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by KristofferC** [comment]
Tell me when you want to register a new Tokenize version.

**Comment by ZacLN** [comment]
Will do, I'll have a go at sorting out the [unicode](https://github.com/KristofferC/Tokenize.jl/issues/88) issue first

**Comment by ZacLN** [comment]
OK I'm going to register an initial release of CSTParser, could you tag a new version of Tokenize @KristofferC ?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/9142

**Comment by ZacLN** [comment]
Thanks!

**Pull request merged**
