### PR TITLE
unparameterize PUNCTUATION

### PR DESCRIPTION
**Pull request by KristofferC**
Against noval branch. Benchmarks show a ~10% parsing improvement and a slight memory allocation reduction.

Maybe you already have this on a local branch but I was bored... :P

### CODE REVIEW

**Comment by ZacLN** [comment]
Yeah, turns out parameters are evil....

**Comment by KristofferC** [comment]
At least when they are used as `if` statements :P

**Comment by ZacLN** [comment]
I just got over excited by them

**Comment by KristofferC** [comment]
BTW, Something like this https://gist.github.com/KristofferC/d8f1cbfbc10bdf7d96d0b3a008a93232 saves ~3 seconds of initial load up time. Not sure if it is worth it.

**Comment by ZacLN** [comment]
Wicked, I'll test all this when I get home and merge. Startup time is the main problem at the moment (wet vscode)

**Pull request merged**
