### PR TITLE
Better support for :incomplete errors

### PR DESCRIPTION
**Pull request by Keno**
Base parsing distinguishes incorrect syntax and incomplete syntax.
For the latter, pressing enter at the repl will give a newline rather
than a parse error. Add the appropriate error kinds and try to emit
them as necessary. FancyDiagnostics has support to hook this into Base.

### CODE REVIEW

**Comment by Keno** [comment]
After this FancyDiagnostics is decently usable if people want to give it a spin. Still a bunch of work to be done to actually give all the diagnostics that JuliaParser knew about of course.

**Comment by davidanthoff** [comment]
@ZacLN Just in terms of release planning: maybe tag a v0.1.0 on master before you merge this, and then this PR will become part of v0.2.0? We don't need any of this for the next VS Code release, and that way we could do the VS Code v0.7.0 release with v0.1.0 of CSTParser, right? @Keno we're trying to finish up the v0.7.0 release for VS Code, so it might be better to not merge big things into the version we are going to use for VS Code, i.e. might be better to slow down churn for that release.

**Comment by ZacLN** [comment]
Yep that sounds like a plan

**Comment by Keno** [comment]
I rebased this.

**Pull request merged**
