### PR TITLE
Fix misc parsing issues

### PR DESCRIPTION
**Pull request by Keno**
The first commit fixes the experience when loading FancyDiagnostic. Rather than falling back to the flisp parser, for certain corner cases, do everything in this package (with FancyDiagnostics, Base.parse calls CSTParser.parse). The next two commits fix various issues that show up in the base comparison test, which now passes. I also went ahead and stripped trailing whitespace in the files that I touched.

### CODE REVIEW

**Comment by Keno** [comment]
One more commit to do unicode normalization.

**Comment by Keno** [comment]
Oh yeah, depends on Tokenize master.

**Comment by ZacLN** [comment]
This fails the string interpolation tests on my machine, does it need the un-comitted Tokenize PR ?

**Comment by KristofferC** [comment]
Yes, I will merge and tag it now

**Comment by ZacLN** [comment]
ta

**Comment by KristofferC** [comment]
Tokenize has been tagged

**Comment by ZacLN** [comment]
Ah it's some triple-quote string tests that are failing, unrelated to that PR afaict

**Comment by Keno** [comment]
Everything should pass with latest Tokenize (it does for me locally).

**Comment by ZacLN** [comment]
Hmm, I can't get it to pass on travis or my own setup. Are you on julia 0.7 perchance?

**Comment by Keno** [comment]
> Are you on julia 0.7 perchance?

No. Can you confirm your Tokenize has https://github.com/KristofferC/Tokenize.jl/pull/95?

**Comment by Keno** [comment]
Hm, I appear to have https://github.com/KristofferC/Tokenize.jl/pull/94 locally also. Maybe that's the issue. Let me check.

**Comment by ZacLN** [comment]
Ah yes, that's what I meant above by the unmerged PR

**Comment by ZacLN** [comment]
Tests pass locally w/ https://github.com/KristofferC/Tokenize.jl/issues/96 so I'll merge when a new `Tokenize` gets tagged

**Comment by davidanthoff** [comment]
Just for reference, we are just waiting for JuliaLang/METADATA.jl#10463 at this point, I believe.

**Comment by KristofferC** [comment]
It's merged.

**Comment by ZacLN** [comment]
ta

**Pull request merged**
