### PR TITLE
Whitespace refactor

### PR DESCRIPTION
**Pull request by Keno**
As discussed on slack, I want to more explicitly identify syntax trivia in the CST. This puts in place the infrastructure to do that. What used to be called `span` is now called `fullspan`. `span` is now the span of the expression excluding any syntax trivia and is a byte range inside `fullspan`. The plan going forward is to use AbstractTrees to implicitly generate a separate tree with stored parents and absolute byte ranges that is easier for consumers to work with, but I'm still playing with that. This PR is just the infrastructure. It passes tests, but I've not added any tests for the correctness of the new information. However, I wanted to get this up ASAP, since it touches many lines of code and is likely to conflict with any other in-progress work.

### CODE REVIEW

**Comment by ZacLN** [comment]
`error_unexpected` needs the `EXPR` constructors updated for fullspan/span

**Comment by Keno** [comment]
I merged your PR, but there's a conflict now. I'll go ahead and rebase this.

**Comment by ZacLN** [comment]
Cool, I'll leave this until Monday to merge

**Comment by Keno** [comment]
There's two errors in the FemtoCleaner logs. Not necessarily caused by this PR, but I'll leave them here anyway for future reference:
```
SERVER ERROR: BoundsError: attempt to access 0-element Array{CSTParser.EXPR,1} at index [0]
Stacktrace:
 [1] pop!(::CSTParser.EXPR{CSTParser.TupleH}) at /opt/pkgs/v0.6/CSTParser/src/spec.jl:47
 [2] parse_comma_sep(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.TupleH}, ::Bool, ::Bool, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/components/functions.jl:150
 [3] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [4] parse_paren(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:197
 [5] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [6] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:63
 [7] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:80 [inlined]
 [8] parse_unary(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.OPERATOR{8,COLON::Tokenize.Tokens.Kind = 540,false}}) at /opt/pkgs/v0.6/CSTParser/src/components/operators.jl:206
 [9] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [10] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:75
 [11] macro expansion at /opt/pkgs/v0.6/CSTParser/src/components/functions.jl:135 [inlined]
 [12] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [13] parse_comma_sep(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.Call}, ::Bool, ::Bool, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/components/functions.jl:131
 [14] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [15] parse_call(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.BinarySyntaxOpCall}) at /opt/pkgs/v0.6/CSTParser/src/components/functions.jl:123
 [16] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [17] parse_compound(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.BinarySyntaxOpCall}) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:126
 [18] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [19] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:91
 [20] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [21] macro expansion at /opt/pkgs/v0.6/CSTParser/src/components/macros.jl:55 [inlined]
 [22] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:124 [inlined]
 [23] parse_macrocall(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/components/macros.jl:54
 [24] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [25] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:78
 [26] parse_doc(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:248
 [27] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [28] macro expansion at /opt/pkgs/v0.6/CSTParser/src/components/modules.jl:20 [inlined]
 [29] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:124 [inlined]
 [30] parse_module(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/components/modules.jl:19
 [31] parse_kw(::CSTParser.ParseState, ::Type{Val{MODULE::Tokenize.Tokens.Kind = 34}}) at /opt/pkgs/v0.6/CSTParser/src/components/modules.jl:5
 [32] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [33] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:61
 [34] parse_doc(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:248
 [35] parse(::CSTParser.ParseState, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:269
 [36] parse(::String, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:219
```
```
SERVER ERROR: UndefVarError: pt not defined
Stacktrace:
 [1] parse_compound(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.InvisBrackets}) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:165
 [2] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [3] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:91
 [4] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:80 [inlined]
 [5] parse_operator(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.BinaryOpCall}, ::CSTParser.EXPR{CSTParser.OPERATOR{11,FWD_SLASH::Tokenize.Tokens.Kind = 609,false}}) at /opt/pkgs/v0.6/CSTParser/src/components/operators.jl:429
 [6] parse_compound(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.BinaryOpCall}) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:138
 [7] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [8] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:91
 [9] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [10] macro expansion at /opt/pkgs/v0.6/CSTParser/src/components/macros.jl:55 [inlined]
 [11] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:124 [inlined]
 [12] parse_macrocall(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/components/macros.jl:54
 [13] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [14] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:78
 [15] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:80 [inlined]
 [16] parse_operator(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.IDENTIFIER}, ::CSTParser.EXPR{CSTParser.OPERATOR{1,EQ::Tokenize.Tokens.Kind = 98,false}}) at /opt/pkgs/v0.6/CSTParser/src/components/operators.jl:214
 [17] parse_compound(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.IDENTIFIER}) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:138
 [18] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [19] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:91
 [20] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [21] parse_block(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.Block}, ::Array{Tokenize.Tokens.Kind,1}, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/components/genericblocks.jl:25
 [22] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [23] parse_if(::CSTParser.ParseState, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/components/if.jl:14
 [24] parse_kw(::CSTParser.ParseState, ::Type{Val{IF::Tokenize.Tokens.Kind = 27}}) at /opt/pkgs/v0.6/CSTParser/src/components/if.jl:1
 [25] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [26] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:61
 [27] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [28] parse_block(::CSTParser.ParseState, ::CSTParser.EXPR{CSTParser.Block}, ::Array{Tokenize.Tokens.Kind,1}, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/components/genericblocks.jl:25
 [29] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:154 [inlined]
 [30] parse_kw(::CSTParser.ParseState, ::Type{Val{FUNCTION::Tokenize.Tokens.Kind = 25}}) at /opt/pkgs/v0.6/CSTParser/src/components/functions.jl:34
 [31] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [32] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:61
 [33] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:49 [inlined]
 [34] macro expansion at /opt/pkgs/v0.6/CSTParser/src/components/macros.jl:55 [inlined]
 [35] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:124 [inlined]
 [36] parse_macrocall(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/components/macros.jl:54
 [37] macro expansion at /opt/pkgs/v0.6/CSTParser/src/utils.jl:182 [inlined]
 [38] parse_expression(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:78
 [39] parse_doc(::CSTParser.ParseState) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:248
 [40] parse(::CSTParser.ParseState, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:269
 [41] parse(::String, ::Bool) at /opt/pkgs/v0.6/CSTParser/src/CSTParser.jl:219
```

**Comment by ZacLN** [comment]
I've fixed the latter error

**Pull request merged**
